# This is a basic workflow to help you get started with Actions
name: AZURE push image and deploy app service
on:
#   push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: democontainer032.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t democontainer032.azurecr.io/democontainer032:${{ github.sha }}
          docker push democontainer032.azurecr.io/democontainer032:${{ github.sha }}
          
      - uses: azure/webapps-deploy@v2
      - with:
          app-name: 'container0321'
          slot-name: '12'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'samples/nginx.azurecr.io/samples/nginx:${{ github.sha }}'
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.34.1
          inlineScript: |
            az webapp deployment slot swap -g onprem-rg -n container0321 --slot 12 \
                  --target-slot production
